"""add image_url to events and notices

Revision ID: 343f7695b561
Revises: 645507e9d015
Create Date: 2026-07-05 17:17:08.098822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '343f7695b561'
down_revision: Union[str, Sequence[str], None] = '645507e9d015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('notices', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'image_url')
    op.drop_column('events', 'image_url')
    # ### end Alembic commands ###
